const fs = require('fs');
const SideToken_v1 = artifacts.require("SideToken_v1");
const Oracle = artifacts.require("Oracle");
const Consumer = artifacts.require("Consumer");

module.exports = async function(deployer, networks, accounts) {
	const sideToken = await SideToken_v1.deployed();
	const oracle = await Oracle.deployed();
	const jobSpec = await getJobSpec();

	return deployer.deploy(Consumer, sideToken.address, oracle.address, jobSpec);
};

/* Reads the configuration file generated by the test runner and returns the ID
   of the job created on the Chainlink node */
function getJobSpec(){
	return new Promise(async function(resolve, reject){
		fs.readFile('../config/config.json', 'utf8', (err, data) => {
			if (err) throw err;
			const jobSpec = web3.utils.utf8ToHex(JSON.parse(data).jobId);
			resolve(jobSpec);
		}).catch(e => {
			reject(e);
		});
	});
}
